Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Models/LocatieViewModel.cs
using LogicaLaag.AlleLocaties;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace AxiGroep_5.Models
{
    public class LocatieViewModel
    {
        [DisplayName("Locatie ID")]
        public int LocatieId { get; set; }
        [DisplayName("Magazijn ID")]
        public int MagazijnId { get; set; }
        [DisplayName("Rij")]
        public int RijNummer { get; set; }
        [DisplayName("Niveau")]
        public int NiveauId { get; set; }
        [DisplayName("Plek")]
        public int PlekId { get; set; }
        [DisplayName("Artikel")]
        public int ArtikelId { get; set; }
        [DisplayName("Is Bezet")]
        public bool IsBezet { get; set; }
        [DisplayName("Aantal")]
        public int AantalInLocatie { get; set; }
    }
}

Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Controllers/LocatieController.cs
using AxiGroep_5.Models;
using DAL;
using LogicaLaag.AlleLocaties;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace AxiGroep_5.Controllers
{
    public class LocatieController : Controller
    {
        LocatieContainer locatieContainer = new LocatieContainer(new LocatieMSSQL());
        Converter converter = new Converter();

        public IActionResult Index()
        {
            List<Locatie> locaties = locatieContainer.LocatiesOphalen();
            List<LocatieViewModel> viewModels = new List<LocatieViewModel>();
            LocatieViewModel viewModel;
            foreach (Locatie locatie in locaties)
            {
                viewModel = converter.LocatieNaarlocatieViewModel(locatie);
                viewModels.Add(viewModel);
            }
            return View(viewModels);
        }

        public IActionResult LocatiesOpArtikel(int artikelId)
        {
            List<Locatie> locaties = locatieContainer.LocatiesOphalenOpArtikelId(artikelId);
            List<LocatieViewModel> locatieViewModels = new List<LocatieViewModel>();
            LocatieViewModel locatieViewModel = new LocatieViewModel();
            foreach (Locatie locatie in locaties)
            {
                locatieViewModel = new LocatieViewModel
                {
                    LocatieId = locatie.LocatieId,
                    MagazijnId = locatie.MagazijnId,
                    RijNummer = locatie.RijNummer,
                    NiveauId = locatie.NiveauId,
                    PlekId = locatie.PlekId,
                    IsBezet = locatie.IsBezet,
                    AantalInLocatie = locatie.AantalInLocatie
                };
                locatieViewModels.Add(locatieViewModel);
            }
            return View(locatieViewModels);
        }

        public IActionResult LocatieAanmaken()
        {
            return View();
        }

        [HttpPost]
        public IActionResult LocatieAanmaken(LocatieViewModel model)
        {
            Locatie locatie = converter.LocatieViewModelNaarLocatie(model);
            locatieContainer.LocatieAanmaken(locatie, 5, 30);
            return RedirectToAction("Index");
        }

        public IActionResult OrderPickenOverzicht(int bestellingID)
        {

            List<Locatie> locaties = locatieContainer.SelectLaagsteAantalInLocatie(bestellingID);

            List<LocatieViewModel> viewmodels = converter.LijstLocatieModelNaarLijstViewModel(locaties);
            return View(viewmodels);
        }

        public IActionResult Details(int id)
        {
            Locatie locatie = locatieContainer.SelecteerLocatieOpId(id);
            LocatieViewModel model = converter.LocatieNaarlocatieViewModel(locatie);
            return View(model);
        }
    }
}

Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Views/Locatie/Details.cshtml
@model AxiGroep_5.Models.LocatieViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Locatie details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocatieId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocatieId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MagazijnId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MagazijnId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RijNummer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RijNummer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NiveauId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NiveauId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlekId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlekId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArtikelId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArtikelId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsBezet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsBezet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AantalInLocatie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AantalInLocatie)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Views/Locatie/Index.cshtml
@model IEnumerable<AxiGroep_5.Models.LocatieViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Alle locaties</h1>

<p>
    <a asp-action="LocatieAanmaken">Nieuwe locatie aanmaken</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LocatieId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MagazijnId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RijNummer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NiveauId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlekId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArtikelId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsBezet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AantalInLocatie)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LocatieId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MagazijnId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RijNummer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NiveauId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlekId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ArtikelId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsBezet)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AantalInLocatie)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id=item.LocatieId }) |
                    @Html.ActionLink("Verwijder", "Delete", new { id=item.LocatieId  })
                </td>
            </tr>
        }
    </tbody>
</table>

Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Views/Locatie/LocatieAanmaken.cshtml
@model AxiGroep_5.Models.LocatieViewModel

@{
    ViewData["Title"] = "LocatieAanmaken";
}

<h1>Locatie Aanmaken</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-controller="Locatie" asp-action="LocatieAanmaken">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MagazijnId" class="control-label"></label>
                <input asp-for="MagazijnId" class="form-control" />
                <span asp-validation-for="MagazijnId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RijNummer" class="control-label"></label>
                <input asp-for="RijNummer" class="form-control" />
                <span asp-validation-for="RijNummer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Locatie" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Views/Locatie/LocatiesOpArtikel.cshtml
@model IEnumerable<AxiGroep_5.Models.LocatieViewModel>

@{
    ViewData["Title"] = "LocatiesOpArtikel";
}

<h1>LocatiesOpArtikel</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LocatieId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MagazijnId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RijNummer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NiveauId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlekId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArtikelId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsBezet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AantalInLocatie)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LocatieId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MagazijnId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RijNummer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NiveauId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlekId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArtikelId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsBezet)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AantalInLocatie)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Views/Locatie/OrderPickenOverzicht.cshtml
@model IEnumerable<AxiGroep_5.Models.LocatieViewModel>

@{
    ViewData["Title"] = "OrderPickenOverzicht";
}

<h1>OrderPickenOverzicht</h1>

<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.RijNummer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NiveauId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlekId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArtikelId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AantalInLocatie)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RijNummer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NiveauId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlekId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArtikelId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AantalInLocatie)
            </td>
        </tr>
}
    </tbody>
</table>