Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Controllers/ArtikelController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AxiGroep_5.Models;
using LogicaLaag;
using DAL;
using Microsoft.AspNetCore.Authorization;

namespace AxiGroep_5.Controllers
{
    [Authorize(Roles = "Manager,Admin,Medewerker")]
    public class ArtikelController : Controller
    {
        public Converter converter = new Converter();
        public IActionResult Index()
        {
            ArtikelContainer container = new ArtikelContainer(new ArtikelMSSQL());
            List<ArtikelViewModel> list = converter.LijstArtikelNaarArtikelViewModel(container.SelecteerArtikels());
            return View(list);
        }
        public IActionResult ArtikelAanmaken()
        {
            ArtikelGroepContainer artikelGroepContainer = new ArtikelGroepContainer(new ArtikelGroepMSSQL());
            List<ArtikelGroepViewModel> artikelGroepViewModelsGeselecteerd = converter.LijstArtikelGroepModelNaarViewModel(artikelGroepContainer.ArtikelGroepBekijken());
            ArtikelAanmakenViewModel artikelAanmakenViewModel = new ArtikelAanmakenViewModel
            {
                artikelGroepViewModels = artikelGroepViewModelsGeselecteerd
            };
            return View(artikelAanmakenViewModel);
        }
        [HttpPost]
        public IActionResult ArtikelAanmaken(ArtikelAanmakenViewModel model)
        {
            ArtikelGroepViewModel artikelGroep = new ArtikelGroepViewModel
            {
                groepID = model.GroepID
            };
            model.artikelViewModel.ArtikelGroepViewmodel = artikelGroep;
            Artikel artikel = converter.ViewModelArtikelNaarModel(model.artikelViewModel);
            artikel.ArtikelAanmaken(artikel, new ArtikelMSSQL());
            return RedirectToAction("index");
        }
        public IActionResult ArtikelAanpassen(int id)
        {
            ArtikelContainer container = new ArtikelContainer(new ArtikelMSSQL());
            ArtikelViewModel artikelViewModelSelected = converter.ModelArtikelNaarViewModel(container.SelecteerArtikel(id));
            ArtikelGroepContainer artikelGroepContainer = new ArtikelGroepContainer(new ArtikelGroepMSSQL());
            List<ArtikelGroepViewModel> artikelGroepViewModelsSelected = converter.LijstArtikelGroepModelNaarViewModel(artikelGroepContainer.ArtikelGroepBekijken());
            ArtikelWijzigenViewmodel artikelWijzigenViewmodel = new ArtikelWijzigenViewmodel
            {
                artikelViewModel = artikelViewModelSelected,
                ArtikelGroepViewModels = artikelGroepViewModelsSelected
            };
            return View(artikelWijzigenViewmodel);
        }
        [HttpPost]
        public IActionResult ArtikelAanpassen(ArtikelWijzigenViewmodel model, int id)
        {
            ArtikelGroepViewModel artikelgroepviewmodel = new ArtikelGroepViewModel
            {
                groepID = model.GroepID
            };
            model.artikelViewModel.ArtikelGroepViewmodel = artikelgroepviewmodel;
            Artikel artikel = converter.ViewModelArtikelNaarModel(model.artikelViewModel);
            artikel.ArtikelID = id;
            artikel.ArtikelUpdaten(artikel, new ArtikelMSSQL());

            return RedirectToAction("index");
        }
        public IActionResult ArtikelDetails(int id)
        {
            ArtikelContainer container = new ArtikelContainer(new ArtikelMSSQL());
            ArtikelViewModel artikelViewModel = converter.ModelArtikelNaarViewModel(container.SelecteerArtikel(id));


            return View(artikelViewModel);
        }
        public IActionResult ArtikelVerwijderen(int id)
        {
            ArtikelContainer container = new ArtikelContainer(new ArtikelMSSQL());
            container.VerwijderArtikel(id);
            return RedirectToAction("index");
        }

    }
}

Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Controllers/KlantController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LogicaLaag;
using DAL;
using AxiGroep_5.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using AxiGroep_5.HelperClasses;
using LogicaLaag.Winkelmandje;

namespace AxiGroep_5.Controllers
{
    public class KlantController : Controller
    {
        Converter converter = new Converter();
        WinkelmandjeContainer container = new WinkelmandjeContainer(new Winkelmandjemssql());
        ArtikelContainer artikelcontainer = new ArtikelContainer(new ArtikelMSSQL());

        public IActionResult Index()
        {
            List<ArtikelViewModel> list = converter.LijstArtikelNaarArtikelViewModel(artikelcontainer.SelecteerArtikels());
            return View(list);
        }

        public IActionResult ToevoegenAanWinkelmandje(string ArtikelNaam, string Beschrijving, double Prijs, int id)
        {
            SessieBehandelaar sessionHandler = new SessieBehandelaar(HttpContext);
            ArtikelViewModel artikel = new ArtikelViewModel(ArtikelNaam, Prijs, Beschrijving, 1, id);
            List<ArtikelViewModel> Winkelmandje = sessionHandler.OphalenWinkelmandje();
            foreach(ArtikelViewModel artikelViewModel in Winkelmandje)
            {
                if(ArtikelNaam == artikelViewModel.Artikelnaam)
                {
                    VerhoogArtikelAantal(ArtikelNaam);
                    return RedirectToAction("index");
                }
            }
            if (Winkelmandje != null)
            {
                Winkelmandje.Add(artikel);
                sessionHandler.ToevoegenWinkelmandje(Winkelmandje);
            }
            return RedirectToAction("index");
        }
        public IActionResult Winkelmandje()
        {
            SessieBehandelaar sessionHandler = new SessieBehandelaar(HttpContext);
            List<ArtikelViewModel> WinkelmandjeArtikelen = sessionHandler.OphalenWinkelmandje();
            double Totaalbedrag = 0;
            foreach(ArtikelViewModel artikelViewModel in WinkelmandjeArtikelen)
            {
                artikelViewModel.TotaalPrijs = artikelViewModel.Prijs * artikelViewModel.Aantal;
                Totaalbedrag += artikelViewModel.TotaalPrijs;
            }
            ViewBag.ArtikelTotaal = Totaalbedrag;
            return View("Winkelmandje",WinkelmandjeArtikelen);
        }

        public IActionResult VerhoogArtikelAantal(string Artikel)
        {
            SessieBehandelaar sessionHandler = new SessieBehandelaar(HttpContext);
            List<ArtikelViewModel> Winkelmandje = sessionHandler.OphalenWinkelmandje();

            foreach(ArtikelViewModel artikel in Winkelmandje)
            if(artikel.Artikelnaam == Artikel)
                {
                    artikel.Aantal++;

                    artikel.TotaalPrijs = artikel.Aantal * artikel.Prijs;
                }
            sessionHandler.ToevoegenWinkelmandje(Winkelmandje);
            return RedirectToAction("Winkelmandje");
        }

        public IActionResult VerlaagArtikelAantal(string Artikel)
        {
            SessieBehandelaar sessionHandler = new SessieBehandelaar(HttpContext);
            List<ArtikelViewModel> Winkelmandje = sessionHandler.OphalenWinkelmandje();

            foreach (ArtikelViewModel artikel in Winkelmandje)
                if (artikel.Artikelnaam == Artikel)
                {
                    artikel.Aantal--;
                    if(artikel.Aantal < 1)
                    {
                        artikel.Aantal = 1;
                    }

                    artikel.TotaalPrijs = artikel.Aantal * artikel.Prijs;
                }
            sessionHandler.ToevoegenWinkelmandje(Winkelmandje);
            return RedirectToAction("Winkelmandje");
        }

        public IActionResult BestelWinkelmandje()
        {
            SessieBehandelaar sessionHandler = new SessieBehandelaar(HttpContext);
            List<ArtikelViewModel> Winkelmandje = sessionHandler.OphalenWinkelmandje();
            List<Artikel> artikels = new List<Artikel>();
            int GebruikerID = Convert.ToInt32(HttpContext.Session.GetString("GebruikerID"));
            foreach(ArtikelViewModel artikelViewModel in Winkelmandje)
            {
                artikels.Add(converter.ViewModelArtikelNaarModelVoorBestellen(artikelViewModel));
            }
            container.BestelWinkelmandje(artikels, GebruikerID);
            return View("Ordercompleted");
        }
    }
}

Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Views/Shared/AdminManagerDashboard.cshtml
@model AxiGroep_5.Models.DataViewModel

@{
    ViewData["Title"] = "Dashboard";
}
<head>
    <style>
        #myProgress {
            width: 100%;
            background-color: #ddd;
            border-radius: 25px;
        }

        #myBar {
            border-radius: 25px;
            width: 10%;
            height: 30px;
            background-color: #7b42fa;
            text-align: center;
            line-height: 30px;
            color: white;
        }
    </style>

    <script>
        window.onload = function () {

            {
                var elem = document.getElementById("myBar");
                var width = 1;
                var id = setInterval(frame, 20);
                function frame() {
                    if (width >= @Math.Round(Model.Percentage)) {
                        clearInterval(id);
                    }
                    if (width >= 100)
                    {
                        clearInterval(id)
                    }
                    else
                    {
                        width++;
                        elem.style.width = width + '%' ;
                        elem.innerHTML = width * 1 + '%' ;
                    }
                }
            }


            var chart = new CanvasJS.Chart("pie", {
                animationEnabled: true,
                exportEnabled: false,
                theme: "light2", // "light1", "light2", "dark1", "dark2"
                title: {
                    text: "Artikelen verkocht deze maand per product"
                },
                axisY: {
                    includeZero: true
                },
                data: [{
                    type: "pie", //change type to bar, line, area, pie, column etc
                    //indexLabel: "{y}", //Shows y value on all Data Points
                    indexLabelFontColor: "#5A5757",
                    indexLabelFontSize: 16,
                    indexLabelPlacement: "outside",
                    dataPoints: [
                      @foreach ( LogicaLaag.Data.Data data in Model.DataIEnum)
                        {
                          <text>{ y: @data.Aantal , label: "@data.Naam" },</text>
                        }
                    ]
                }]
            });

            var chart2 = new CanvasJS.Chart("chartContainer", {
                animationEnabled: true,
                theme: "light2", // "light1", "light2", "dark1", "dark2"
                title: {
                    text: "Artikelen verkocht deze maand per groep"
                },
                axisY: {
                    title: "Aantal"
                },
                data: [{
                    type: "column",
                    dataPoints: [
                      @foreach ( LogicaLaag.Data.Data data in Model.DataIEnum2)
                        {
                          <text>{ y: @data.Aantal , label: "@data.Naam" },</text>
                        }
                    ]
                }]
            });
            chart.render();
            chart2.render();
        }</script>
</head>
<h1>@ViewData["Title"]</h1>
<div class="card" style="border-style:none">
    <div class="col-sm-7" style="position:absolute; right:20px; bottom:-120px">
        <div id="pie"></div>
        <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    </div>
</div>

<div class="card" style="border-style:none">
    <div class="col-sm-3 align-right" style="bottom:-120px">
        <div id="chartContainer"></div>
        <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    </div>
</div>


<h4>Totale vulling magazijn in procent</h4>

<div id="myProgress">
    <div id="myBar" style="width: 1%;">1%</div>
</div>

Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Views/Shared/MedewerkerDashboard.cshtml
@model IEnumerable<AxiGroep_5.Models.KlantBestellingModel>

<h1>Oudste bestellingen</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BestellingID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Artikelaantal)
            </th>
            <th></th>
        </tr>
    </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BestellingID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Artikelaantal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DagTijd)
                </td>
                <td>
                    @Html.ActionLink("Details", "KlantBestellingDetails", "KlantBestelling", new { bestellingid = item.BestellingID })
                </td>

            </tr>
        }

    

</table>

Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Magazijn App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/Images/road to een blije david.png" style="width: 80px; height:37px;" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AxiGroep_5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Views/Shared/_KlantLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Magazijn App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Klant" asp-action="Index"><img src="/Images/road to een blije david.png" style="width: 80px; height:37px;" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Klant" asp-action="Index">Artikelen</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <a class="nav-link text-dark" asp-action="Winkelmandje" asp-controller="Klant">Winkelmandje</a>
                </div>
                    <div>
                        @Html.ViewContext.HttpContext.Session.GetString("GebruikerEmail")
                    </div>
                    <div class="nav-item justify-content-space-around">
                        <div class="justify-content-space-around">
                            <div>
                                <a class="nav-link text-dark" asp-action="Logout" asp-controller="Account">Uitloggen</a>
                            </div>
                        </div>
                    </div>
                </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AxiGroep_5 - 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Views/Shared/_ManagerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Magazijn App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="AdminManagerDashboard"><img src="/Images/road to een blije david.png" style="width: 80px; height:37px;" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Levering" asp-action="Index">Levering verwerken</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artikel" asp-action="Index">Artikelen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ArtikelGroep" asp-action="Index">ArtikelenGroepen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Management" asp-action="Index">Beheer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Index" asp-controller="KlantBestelling">Bestellingen</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                    <div>
                        @Html.ViewContext.HttpContext.Session.GetString("GebruikerEmail")
                    </div>
                    <div class="nav-item justify-content-space-around">
                        <div class="justify-content-space-around">
                            <div>
                                <a class="nav-link text-dark" asp-action="Logout" asp-controller="Account">Uitloggen</a>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AxiGroep_5 - 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Views/Shared/_MedewerkerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Magazijn App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="KlantBestelling" asp-action="DrieOudsteBestellingen"><img src="/Images/road to een blije david.png" style="width: 80px; height:37px;" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Levering" asp-action="Index">Levering verwerken</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artikel" asp-action="Index">Artikelen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ArtikelGroep" asp-action="Index">ArtikelenGroepen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Index" asp-controller="KlantBestelling">Bestellingen</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                    <div>
                        @Html.ViewContext.HttpContext.Session.GetString("GebruikerEmail")
                    </div>
                    <div class="nav-item justify-content-space-around">
                        <div class="justify-content-space-around">
                            <div>
                                <a class="nav-link text-dark" asp-action="Logout" asp-controller="Account">Uitloggen</a>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
</nav>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AxiGroep_5 - 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>