Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Controllers/KlantBestellingController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AxiGroep_5.Models;
using LogicaLaag.KlantBestelling;
using DAL;
using Microsoft.AspNetCore.Authorization;
using LogicaLaag.AlleLocaties;

namespace AxiGroep_5.Controllers
{
    [Authorize(Roles = "Manager,Admin,Medewerker")]
    public class KlantBestellingController : Controller
    {
        KlantBestellingContainer container = new KlantBestellingContainer(new KlantBestellingMSSQL());
        LocatieContainer locatieContainer = new LocatieContainer(new LocatieMSSQL());
        public Converter converter = new Converter();

        public IActionResult Index()
        {
            List<KlantBestellingModel> klantBestellingen = converter.KlantBestellingNaarKlantBestellingModel(container.GetKlantBestellingen());
            return View("KlantBestellingOverzicht", klantBestellingen);
        }
        public IActionResult KlantBestellingDetails(int bestellingid)
        {
            List<KlantBestellingModel> klantBestellingen = converter.KlantBestellingNaarKlantBestellingModel(container.GetBestellingDetails(bestellingid));
            return View("KlantBestellingDetails", klantBestellingen);
        }
        public IActionResult OrderPickenOverzicht(int bestellingid)
        {

            return RedirectToAction("OrderPickenOverzicht", new { controller = "Locatie", Action = "OrderPickenOverzicht", bestellingid = bestellingid });
        }

        public IActionResult BestellingAfronden(int bestellingid)
        {
            List<KlantBestelling> klantBestellingen = container.GetBestellingDetails(bestellingid);
            List<Tuple<Locatie, int>> locatiesMetAantal = new List<Tuple<Locatie, int>>();
            List<int> artikelIDs = new List<int>();
            foreach (KlantBestelling klantBestelling in klantBestellingen)
            {
                artikelIDs.Add(klantBestelling.BesteldeArtikelID);
            }
            List<Locatie> locaties = locatieContainer.SelectLaagsteAantalInLocatie(bestellingid);
            foreach (Locatie locatie in locaties)
            {
                foreach (KlantBestelling bestelling in klantBestellingen)
                {
                    if(locatie.ArtikelId == bestelling.BesteldeArtikelID)
                    {
                        Tuple<Locatie, int> tuple = new Tuple<Locatie, int>(locatieContainer.SelecteerLocatieOpId(locatie.LocatieId), locatie.AantalInLocatie);
                        locatiesMetAantal.Add(tuple);
                    }
                }
            }
            if (!locatieContainer.VoorraadBijwerkenNaBestelling(locatiesMetAantal))
            {
                return RedirectToAction();
            }
            container.BestellingAfronden(bestellingid);
            return RedirectToAction("Index");
        }

        public IActionResult DrieOudsteBestellingen()
        {

            List<KlantBestellingModel> klantBestellingModels = new List<KlantBestellingModel>();
            List<KlantBestellingModel> klantBestellingen = converter.KlantBestellingNaarKlantBestellingModel(container.GetKlantBestellingen());
            for (int i = 0; i < 3; i++)
            {
                klantBestellingModels.Add(klantBestellingen[i]);
            }
            return View("MedewerkerDashboard", klantBestellingModels);
        }
    }
}

Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Views/KlantBestelling/KlantBestellingDetails.cshtml
@model IEnumerable<AxiGroep_5.Models.KlantBestellingModel>

@{
    ViewData["Title"] = "Bestelling details";
}

<h1>Bestelling</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ArtikelNaam)
            </th>
            <th>
                Orderpick aantal
            </th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ArtikelNaam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Artikelaantal)
            </td>
        </tr>
    }
</table>

@Html.ActionLink("Terug", "Index")

Jaar 1 FHICT/ASP.Net Groepsproject/AxiGroep-5/Views/KlantBestelling/KlantBestellingOverzicht.cshtml
@model IEnumerable<AxiGroep_5.Models.KlantBestellingModel>

@{
    ViewData["Title"] = "Bestelling overzicht";
}

<h1>Overzicht</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BestellingID)
            </th>
            <th>
                Aantal verschillende producten
            </th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.BestellingID)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Artikelaantal)
    </td>

    <td>
        @Html.ActionLink("Details", "KlantBestellingDetails", "KlantBestelling", new { bestellingid = item.BestellingID } )
        @Html.ActionLink("| Afronden", "BestellingAfronden", "KlantBestelling", new { bestellingid = item.BestellingID}, new { onclick = "return confirm('Weet je zeker dat je de bestelling wilt afronden?');" })
        @Html.ActionLink("| OrderPicker overzicht", "OrderPickenOverzicht",   new { bestellingid = item.BestellingID})
    </td>
</tr>
    }

</table>