Jaar 1 FHICT/ASP.Net Individueel project/GuitarTabASP/Models/MuziekNummerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GuitarTabASP.Models
{
    public class MuziekNummerViewModel
    {
        
        public string Naam { get; set; }
        public string Tab { get; set; }
        public string Type { get; set; }
        public string Beschrijving { get; set; }
        public int NummerID { get; set; }
        public int userid { get; set; }
        public string youtubelink { get; set; }
        public NummerRatingViewModel rating { get; set; }
        public Uri youtubeUrl
        {
            get
            {
                if(Uri.IsWellFormedUriString(youtubelink,UriKind.Absolute))
                {
                    Uri uri = new Uri(this.youtubelink);
                    return uri;
                }
                else
                {

                    return null;
                }
            }
        }
    }
}

Jaar 1 FHICT/ASP.Net Individueel project/GuitarTabASP/Controllers/MuziekNummerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Logic_layer;
using DAL.Layer;
using GuitarTabASP.Models;
using GuitarTabASP.ViewModelConverters;
using Microsoft.AspNetCore.Http;
using DAL_laag;

namespace GuitarTabASP.Controllers
{
    public class MuziekNummerController : Controller
    {
        MuziekNummerModelConverter converter = new MuziekNummerModelConverter();
        public IActionResult Index()
        {
            MuziekNummerContainer container = new MuziekNummerContainer(new MuziekNummerDAL());
            List<MuziekNummerViewModel> viewModels = converter.ModelListToViewModelList(container.Selectnummers());
            return View(viewModels);
        }
        public IActionResult CreateNummer()
        {
            if(HttpContext.Session.GetInt32("UserID")!=null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login","User");

            }
        }
        [HttpPost]
        public IActionResult CreateNummer(MuziekNummerViewModel muziekNummerViewModel)
        {
        
                Muzieknummer muzieknummer = converter.ViewmodelToModel(muziekNummerViewModel);
                MuziekNummerContainer muziekNummerContainer = new MuziekNummerContainer(new MuziekNummerDAL());
                muzieknummer.userID = (int)HttpContext.Session.GetInt32("UserID");
                muziekNummerContainer.InsertNummer(muzieknummer);
                return View();
            
        }
        public IActionResult ViewNummer(int id)
        {
            MuziekNummerContainer container = new MuziekNummerContainer(new MuziekNummerDAL());
            MuziekNummerViewModel muziekNummerViewModel = converter.ModelToViewModel(container.SelectNummer(id));
            muziekNummerViewModel.NummerID = id;
            ReactieModelConverter reactieModelConverter = new ReactieModelConverter();
            ReactieContainer reactieContainer = new ReactieContainer(new ReactieDAL());
            List<ReactieViewModel> reactieViewModels = reactieModelConverter.ListModelNaarViewModel(reactieContainer.SelectCommentsVanNummer(id));

            MuziekNummerDetailsMetReacties muziekNummerDetailsMetReacties = new MuziekNummerDetailsMetReacties
            {
                muziekNummerViewModel = muziekNummerViewModel,
                reactieViewModels = reactieViewModels
            };
            return View(muziekNummerDetailsMetReacties);
        }
        public IActionResult AddOrUpdateNummerRating(int rating, int TargetNummerID)
        {

            if (HttpContext.Session.GetInt32("UserID") != null)
            {
                RatingContainer container = new RatingContainer(new RatingDAL());
                Rating userrating = new Rating(rating, TargetNummerID, (int)HttpContext.Session.GetInt32("UserID"), new RatingDAL());

                if (!container.HasUserRatedNummerYet((int)HttpContext.Session.GetInt32("UserID"), TargetNummerID))
                {
                    userrating.InsertNummerRating( new RatingDAL());
                    return RedirectToAction("ViewNummer", "MuziekNummer", new { id = TargetNummerID });
                }
                else
                {
                    userrating.UpdateNummerRating( new RatingDAL());
                    return RedirectToAction("ViewNummer", "MuziekNummer", new { id = TargetNummerID });
                }
            }
            else
            {
                return RedirectToAction("ViewNummer", "MuziekNummer", new { id = TargetNummerID });
            }
        }
        public IActionResult EditNummer(int id)
        {
            if(HttpContext.Session.GetInt32("UserID") !=null)
            {
                MuziekNummerContainer container = new MuziekNummerContainer(new MuziekNummerDAL());
                MuziekNummerViewModel muziekNummerViewModel = converter.ModelToViewModel(container.SelectNummer(id));
                if (muziekNummerViewModel.userid != (int)HttpContext.Session.GetInt32("UserID"))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    HttpContext.Session.SetInt32("NummerID", muziekNummerViewModel.NummerID);
                    return View(muziekNummerViewModel);
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }

        }
        [HttpPost]
        public IActionResult EditNummer(MuziekNummerViewModel muziekNummerViewModel)
        {
            muziekNummerViewModel.NummerID = (int)HttpContext.Session.GetInt32("NummerID");
            Muzieknummer muzieknummer = converter.ViewmodelToModel(muziekNummerViewModel);
            MuziekNummerContainer container = new MuziekNummerContainer(new MuziekNummerDAL());
            container.UpdateNummer(muzieknummer);
            return View();
        }
        public IActionResult DeleteNummer(int id)
        {
            if(HttpContext.Session.GetInt32("UserID")!=null)
            {
                MuziekNummerContainer container = new MuziekNummerContainer(new MuziekNummerDAL());
                
                return View();
            }
            else
            {
                return RedirectToAction("Login","User");
            }
        }
        public IActionResult SearchTerm(string zoekterm)
        {
            MuziekNummerContainer cont = new MuziekNummerContainer(new MuziekNummerDAL());
            List<MuziekNummerViewModel> viewModels = converter.ModelListToViewModelList(cont.SelectNummersWithQuery(zoekterm));
            return View("Index", viewModels);
        }
    }
}

Jaar 1 FHICT/ASP.Net Individueel project/GuitarTabASP/Controllers/ReactieController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GuitarTabASP.Models;
using Logic_layer;
using GuitarTabASP.ViewModelConverters;
using DAL_laag;
using Microsoft.AspNetCore.Http;


namespace GuitarTabASP.Controllers
{
    public class ReactieController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult MaakComment(int Id)
        {
            HttpContext.Session.SetInt32("NummerID", Id);
            return View();
        }
        [HttpPost]
        public IActionResult MaakComment(ReactieViewModel reactieViewModel)
        {
            ReactieModelConverter converter = new ReactieModelConverter();
            reactieViewModel.PlaatsTijd = DateTime.Now;
            reactieViewModel.NummerID = (int)HttpContext.Session.GetInt32("NummerID");
            HttpContext.Session.Remove("NummerID");

            Reactie reactie = converter.ViewModelNaarModel(reactieViewModel);
            User user = new User((int)HttpContext.Session.GetInt32("UserID"));
            reactie.user = user;
            reactie.InsertReactie( new ReactieDAL());
            return RedirectToAction("ViewNummer","MuziekNummer",new { id = reactie.NummerID });
        }
        public IActionResult DeleteComment(int id, int nummerid)
        {

            ReactieContainer reactieContainer = new ReactieContainer(new ReactieDAL());
            reactieContainer.DeleteComment(id);
            return RedirectToAction("ViewNummer","MuziekNummer", new { id = nummerid});
        }
    }
}

Jaar 1 FHICT/ASP.Net Individueel project/GuitarTabASP/Views/MuziekNummer/CreateNummer.cshtml
@model GuitarTabASP.Models.MuziekNummerViewModel

@{
    ViewData["Title"] = "MuziekNummerCreate";
}

<h1>Maak nummer aan</h1>

<h4>Voer gegevens van het nummer in.</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="CreateNummer" asp-controller="MuziekNummer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tab" class="control-label"></label>
                <input asp-for="Tab" class="form-control" />
                <span asp-validation-for="Tab" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Beschrijving" class="control-label"></label>
                <input asp-for="Beschrijving" class="form-control" />
                <span asp-validation-for="Beschrijving" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="youtubelink" class="control-label"></label>
                <input asp-for="youtubelink" class="form-control"/>
                <span asp-validation-for="youtubelink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Jaar 1 FHICT/ASP.Net Individueel project/GuitarTabASP/Views/MuziekNummer/EditNummer.cshtml
@model GuitarTabASP.Models.MuziekNummerViewModel

@{
    ViewData["Title"] = "EditNummer";
}

<h1>Pas nummer aan</h1>

<h4>Update gegevens:</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditNummer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tab" class="control-label"></label>
                <input asp-for="Tab" class="form-control" />
                <span asp-validation-for="Tab" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Beschrijving" class="control-label"></label>
                <input asp-for="Beschrijving" class="form-control" />
                <span asp-validation-for="Beschrijving" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="youtubelink" class="control-label"></label>
                <input asp-for="youtubelink" class="form-control" />
                <span asp-validation-for="youtubelink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Jaar 1 FHICT/ASP.Net Individueel project/GuitarTabASP/Views/MuziekNummer/Index.cshtml
@model IEnumerable<GuitarTabASP.Models.MuziekNummerViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Zoek nummers</h1>

<p>
    <a asp-action="CreateNummer">Maak nummer aan.</a>
</p>


<form asp-action="SearchTerm">
      <div class=" form-group">
          <input name="zoekterm" id="zoekterm" type="text" />
    </div>
    <div class=" form-group">
         <input type="submit"value="zoekterm" class="btn btn-primary"/>
    </div>
    </form>
 <table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tab)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Beschrijving)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Naam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tab)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Beschrijving)
            </td>
            @if (Html.ViewContext.HttpContext.Session.GetInt32("UserID") != null)
            {
                @if (item.userid == Convert.ToInt32(Html.ViewContext.HttpContext.Session.GetInt32("UserID")))
                {
                    <td>
                        @Html.ActionLink("Edit", "EditNummer", new { /* id=item.PrimaryKey */id = item.NummerID }) |
                        @Html.ActionLink("Details", "ViewNummer", new { /* id=item.PrimaryKey */id = item.NummerID }) |
                    </td>
                }
                else
                {
                    <td>
                        @Html.ActionLink("Details", "ViewNummer", new { /* id=item.PrimaryKey */id = item.NummerID })
                    </td>
                }
            }
            else
            {
                <td>
                    @Html.ActionLink("Details", "ViewNummer", new { /* id=item.PrimaryKey */id = item.NummerID })
                </td>
            }

        </tr>
        }
    </tbody>
</table>

Jaar 1 FHICT/ASP.Net Individueel project/GuitarTabASP/Views/MuziekNummer/ViewNummer.cshtml
@model GuitarTabASP.Models.MuziekNummerDetailsMetReacties


@{
    ViewData["Title"] = "ViewNummer";
}

<h1>Voeg rating toe.</h1>

<form method="post" asp-action="AddOrUpdateNummerRating" asp-controller="MuziekNummer">

    <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="rating">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
    </select>
    <input type="hidden" value="@Model.muziekNummerViewModel.NummerID" name="TargetNummerID" />
    <div class="form-group">
        <input type="submit" value="go" class="btn btn-primary" />
    </div>
</form>
<h1>Nummer weegave</h1>

<div>
    <h4></h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.muziekNummerViewModel.Naam)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.muziekNummerViewModel.Naam)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.muziekNummerViewModel.Tab)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.muziekNummerViewModel.Tab)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.muziekNummerViewModel.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.muziekNummerViewModel.Type)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.muziekNummerViewModel.Beschrijving)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.muziekNummerViewModel.Beschrijving)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.muziekNummerViewModel.rating.rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.muziekNummerViewModel.rating.rating)
        </dd>

    </dl>
</div>
@if (Model.muziekNummerViewModel.youtubeUrl != null)
{
    <iframe width="420" height="315"
        src="@Model.muziekNummerViewModel.youtubeUrl">
    </iframe>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.reactieViewModels[1].UserViewmodel.Gebruikersnaam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.reactieViewModels[1].Comment)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.reactieViewModels)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserViewmodel.Gebruikersnaam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Comment)
                </td>
                @if (Html.ViewContext.HttpContext.Session.GetInt32("UserID") == item.UserViewmodel.userID)
                {
                    <td>
                        @Html.ActionLink("Delete", "DeleteComment", "Reactie", new { id = item.ReactieID, nummerid = item.NummerID })
                    </td>
                }
            </tr>
        }
    </tbody>
</table>
@if (Html.ViewContext.HttpContext.Session.GetInt32("UserID") != null)
{
    if (Html.ViewContext.HttpContext.Session.GetInt32("UserID") == Model.muziekNummerViewModel.userid)
    {
        <div>
            @Html.ActionLink("Edit", "EditNummer", new { /* id = Model.PrimaryKey */id = Model.muziekNummerViewModel.NummerID }) |
            @Html.ActionLink("Reactie Toevoegen", "MaakComment", "Reactie", new { id = Model.muziekNummerViewModel.NummerID }) |
            <a asp-action="Index">Back to List</a>
        </div>
    }
    else
    {
        <div>
            @Html.ActionLink("Reactie Toevoegen", "MaakComment", "Reactie", new { id = Model.muziekNummerViewModel.NummerID }) |
            <a asp-action="Index">Back to List</a>
        </div>
    }
}
else
{
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
}